### PR TITLE
Add latest pedantic lints

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by kevmoo** [comment]
@natebosch – travis is now green

**Comment by kevmoo** [comment]
> Why aren't we importing the file from the pedantic package?

Because mono-repo. There's no go way to do it in the root of the repo and have it work for sub packages.

Same w/ pkg:build, right?

**Comment by natebosch** [comment]
> Same w/ pkg:build, right?

Oh, yeah probably.

**Pull request merged**
