### PR TITLE
WIP: Trying to support the latest version of pkg/build

### PR DESCRIPTION
**Pull request by kevmoo**
See failures – your bug or mine?

### CODE REVIEW

**Comment by natebosch** [comment]
It's entirely possible the new build_runner slowed things down though I wouldn't expect by much - is it deadlocking altogether? If so it's probably a build_runner bug

**Comment by kevmoo** [comment]
I just pushed a patch to that PR that sets the exit code

**Comment by kevmoo** [comment]
@natebosch see here https://travis-ci.org/dart-lang/json_serializable/jobs/264799208#L528

**Comment by natebosch** [comment]
Definitely a bug in build_runner.

**Comment by natebosch** [comment]
Ok, pub upgrade and this should work now.

**Pull request merged**
