### PR TITLE
Fix typo field name between the comments.

### PR DESCRIPTION
**Pull request by zhengxiaoyao0716**
generate_to_json_function => generateToJsonFunction

### CODE REVIEW

**Comment by zhengxiaoyao0716** [comment]
I signed it!

**Comment by zhengxiaoyao0716** [comment]
@kevmoo Thanks your suggestion, although I could, but maybe it's not a nice idea, for the other codes not use the `[]`. If you sure we should change it use [] syntax, maybe the other codes should changed too?

image
image
image

**Comment by kevmoo** [comment]
If you want to dive in there, that'd be great!

**Comment by kevmoo** [comment]
Closing out per discussion.

**Pull request closed without merging**
