### PR TITLE
Ignore use of CastError - deprecated in Dart 2.8.0-dev.18

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
Feel free to squash/merge and delete the branch if you're happy

**Comment by natebosch** [comment]
I didn't realize some of these were test/example only. Anything outside of lib code could be moved to `TypeError` if you want.

**Comment by kevmoo** [comment]
> I didn't realize some of these were test/example only. Anything outside of lib code could be moved to `TypeError` if you want.

Not if we want to keep testing on old SDKs, though – right?

**Comment by natebosch** [comment]
> Not if we want to keep testing on old SDKs, though – right?

Correct. I'm not sure how critical it is that the `example/` directory runs on old SDKs...

**Pull request merged**
